import { Scenario } from '@/types';

export const igboScenarios: Scenario[] = [
  {
    id: 'igbo-market',
    language: 'igbo',
    title: 'Ahịa',
    titleYoruba: 'Ahịa',
    description: 'Bargain for fresh produce at a busy Onitsha market.',
    icon: '🛒',
    context: 'You are shopping at a busy market in Onitsha.',
    aiRole: 'Market Trader',
    aiRoleYoruba: 'Onye Ahịa',
    starterPrompt: 'Ndewo! Ọ dị mma ịhụ gị. Gwa m ihe ọ bụ ihe ị chọrọ taa.',
    difficulty: 'beginner',
    gender: 'female',
  },
  {
    id: 'igbo-family',
    language: 'igbo',
    title: 'Ezinụlọ',
    titleYoruba: 'Ezinụlọ',
    description: 'Catch up with a family elder after a long time away.',
    icon: '🏡',
    context: 'You have returned to your village and are greeting your uncle.',
    aiRole: 'Uncle',
    aiRoleYoruba: 'Nnanna',
    starterPrompt: 'Nnọọ, nwa m! Anyị ataghị ahụ gị ogologo oge. Bịa ka anyị were oge kwuo okwu.',
    difficulty: 'beginner',
    gender: 'male',
  },
  {
    id: 'igbo-restaurant',
    language: 'igbo',
    title: 'Ụlọ Oriri',
    titleYoruba: 'Ụlọ Oriri',
    description: 'Order a meal at a local Igbo restaurant.',
    icon: '🍲',
    context: 'You are at a local restaurant in Enugu looking at the menu.',
    aiRole: 'Waiter',
    aiRoleYoruba: 'Onye Ọrụ',
    starterPrompt: 'Nnọọ n\'ụlọ oriri anyị. Gwa m ihe ị chọrọ iri taa.',
    difficulty: 'intermediate',
    gender: 'male',
  },
];
